# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Semctl < Formula
  desc "A command line interface for Semaphore UI."
  homepage "https://github.com/moep90/semaphore-cli"
  version "0.6.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Moep90/semctl/releases/download/v0.6.4/semctl_Darwin_x86_64.tar.gz"
      sha256 "dd34f054aeb13761192af87ce0628f4308b8520b6ece6a71ee1019f1ef18f361"

      define_method(:install) do
        bin.install "semctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Moep90/semctl/releases/download/v0.6.4/semctl_Darwin_arm64.tar.gz"
      sha256 "ccd0f4afc79a3a0e3d77391c7f6febf9246184b9a9c5df3b7e12301c5b8d4b91"

      define_method(:install) do
        bin.install "semctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Moep90/semctl/releases/download/v0.6.4/semctl_Linux_x86_64.tar.gz"
      sha256 "529602d36d27428ab34e4e093f722e727014d2f77cd4a8351bd0e4af396fbe13"
      define_method(:install) do
        bin.install "semctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Moep90/semctl/releases/download/v0.6.4/semctl_Linux_arm64.tar.gz"
      sha256 "6b217586926c2a9912f051912d51715c01e0eaee42afcdd4210e6b29d24ac7f2"
      define_method(:install) do
        bin.install "semctl"
      end
    end
  end

  test do
    system "#{bin}/semctl", "version"
  end
end
